<?php

function custom_following_follow_networks_alter(&$networks, $uid = 0){
    $networks[$uid]['imdb'] = array(
        'title' => t('IMDB'),
        'domain' => 'imdb.com',
    );
    $networks[$uid]['drupal'] = array(
        'title' => t('Drupal.org'),
        'domain' => 'drupal.org',
    );
    $networks[$uid]['etsy'] = array(
        'title' => t('Etsy'),
        'domain' => 'etsy.com',
    );
    $networks[$uid]['redbubble'] = array(
        'title' => t('Redbubble'),
        'domain' => 'redbubble.com',
    );
}

// function custom_following_page_build(&$page) {
//     drupal_flush_all_caches();
// }
