<?php
function simple_content_form_alter(&$form, &$form_state, $form_id){
    global $user;

    // if(in_array('moderator', $user->roles)) {
        if(
            $form_id == 'recipe_node_form' ||
            $form_id == 'awards_node_form' ||
            $form_id == 'news_node_form' ||
            $form_id == 'tips_and_tricks_node_form'
        ){

            unset($form['revision_information']);
            $form['revision_information'] = array(
               '#type' => 'hidden',
            );

            unset($form['path']);
            $form['path'] = array(
               '#type' => 'hidden',
            );

            unset($form['comment_settings']);
            $form['comment_settings'] = array(
               '#type' => 'hidden',
            );

            unset($form['author']);
            $form['author'] = array(
               '#type' => 'hidden',
            );

            unset($form['options']);
            $form['options'] = array(
               '#type' => 'hidden',
            );

            unset($form['additional_settings']);
            $form['additional_settings'] = array(
               '#type' => 'hidden',
            );

            unset($form['menu']);
            $form['menu'] = array(
               '#type' => 'hidden',
            );
        }
   // }
}
